#!/usr/bin/env python3
"""Generate the Generation I move table from the PokeAPI-sourced CSV."""

from __future__ import annotations

import argparse
import json
from dataclasses import dataclass
from pathlib import Path

PROVENANCE = "# PokeAPI https://pokeapi.co/api/v2 - generation-i / red-blue"
HEADERS = ("id", "name", "type", "power", "accuracy", "pp", "damage_class", "ailment", "ailment_chance")
MOVE_COUNT = 165
TYPES = {
    "Normal", "Fire", "Water", "Electric", "Grass", "Ice", "Fighting", "Poison", "Ground",
    "Flying", "Psychic", "Bug", "Rock", "Ghost", "Dragon", "Dark", "Steel", "Fairy",
}
DAMAGE_CLASSES = {"physical": "Physical", "special": "Special", "status": "Status"}
AILMENTS = {"None", "Paralysis", "Sleep", "Freeze", "Burn", "Poison", "Confusion"}


class DataError(RuntimeError):
    pass


@dataclass(frozen=True)
class Move:
    move_id: int
    name: str
    type_: str
    power: int
    accuracy: int
    pp: int
    category: str
    ailment: str
    ailment_chance: int


def _read_rows(path: Path) -> list[dict[str, str]]:
    import csv

    with path.open("r", encoding="utf-8", newline="") as source:
        provenance = source.readline().rstrip("\r\n")
        if provenance != PROVENANCE:
            raise DataError("moves CSV provenance does not match the pinned PokeAPI source")
        reader = csv.DictReader(source)
        if tuple(reader.fieldnames or ()) != HEADERS:
            raise DataError("moves CSV headers do not match the schema")
        return list(reader)


def load_moves(path: Path) -> list[Move]:
    output: list[Move] = []
    for row in _read_rows(path):
        try:
            move_id = int(row["id"])
            power = int(row["power"])
            accuracy = int(row["accuracy"])
            pp = int(row["pp"])
            ailment_chance = int(row["ailment_chance"])
        except (TypeError, ValueError) as error:
            raise DataError("moves CSV contains a non-numeric field") from error
        if move_id != len(output) + 1:
            raise DataError("move IDs must be continuous from 1")
        if not row["name"] or row["type"] not in TYPES:
            raise DataError(f"move {move_id}: invalid name or type")
        if not (0 <= power <= 255) or not (0 <= accuracy <= 100) or not (0 <= pp <= 40):
            raise DataError(f"move {move_id}: power/accuracy/pp out of range")
        if row["damage_class"] not in DAMAGE_CLASSES:
            raise DataError(f"move {move_id}: unknown damage class {row['damage_class']!r}")
        if row["ailment"] not in AILMENTS or not (0 <= ailment_chance <= 100):
            raise DataError(f"move {move_id}: invalid ailment or ailment_chance")
        output.append(
            Move(
                move_id,
                row["name"],
                row["type"],
                power,
                accuracy,
                pp,
                DAMAGE_CLASSES[row["damage_class"]],
                row["ailment"],
                ailment_chance,
            )
        )
    if len(output) != MOVE_COUNT:
        raise DataError(f"expected {MOVE_COUNT} moves, found {len(output)}")
    return output


def generate(moves: list[Move]) -> str:
    lines = [
        "// Generated by scripts/generate_pokemon_moves.py. Do not edit.",
        "#pragma once",
        "",
        "namespace pokemon::generated {",
        "",
    ]
    for move in moves:
        lines.append(f"static const char MOVE_NAME_{move.move_id:03d}[] = {json.dumps(move.name, ensure_ascii=False)};")
    lines.extend(("", "static const MoveData MOVES[] = {"))
    for move in moves:
        lines.append(
            "    MoveData{"
            f"{move.move_id}, MOVE_NAME_{move.move_id:03d}, PokemonType::{move.type_}, "
            f"{move.power}, {move.accuracy}, {move.pp}, MoveCategory::{move.category}, "
            f"Ailment::{move.ailment}, {move.ailment_chance}"
            "},"
        )
    lines.extend(
        (
            "};",
            "",
            "static_assert(sizeof(MOVES) / sizeof(MOVES[0]) == MOVE_COUNT);",
            "",
            "}  // namespace pokemon::generated",
            "",
        )
    )
    return "\n".join(lines)


def main() -> int:
    root = Path(__file__).resolve().parents[1]
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", type=Path, default=root / "scripts/data/pokemon-moves.csv")
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    rendered = generate(load_moves(args.input))
    if args.check:
        if not args.output.exists() or args.output.read_text(encoding="utf-8") != rendered:
            raise DataError(f"generated move table is stale: {args.output}")
        return 0
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(rendered, encoding="utf-8", newline="\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
