#!/usr/bin/env python3
"""Generate the gym leader / Elite Four table from the hand-authored CSV."""

from __future__ import annotations

import argparse
import csv
import json
from dataclasses import dataclass
from pathlib import Path

PROVENANCE = "# Hand-authored: Pokemon Red gym leaders and Elite Four, teams trimmed to 2-3 Pokemon (each battle turn is a full e-ink refresh)"
HEADERS = ("order", "leader", "badge", "type", "team")
GYM_COUNT = 12
MAX_TEAM_SIZE = 3
SPECIES_COUNT = 151
TYPES = {
    "Normal", "Fire", "Water", "Electric", "Grass", "Ice", "Fighting", "Poison", "Ground",
    "Flying", "Psychic", "Bug", "Rock", "Ghost", "Dragon", "Dark", "Steel", "Fairy",
}


class DataError(RuntimeError):
    pass


@dataclass(frozen=True)
class TeamMember:
    species_id: int
    level: int


@dataclass(frozen=True)
class Gym:
    order: int
    leader: str
    badge: str  # "" for Elite Four
    type_: str
    team: tuple[TeamMember, ...]


def parse_team(value: str, order: int) -> tuple[TeamMember, ...]:
    members: list[TeamMember] = []
    for encoded in value.split(";"):
        fields = encoded.split(":")
        if len(fields) != 2:
            raise DataError(f"gym {order}: invalid team member {encoded!r}")
        try:
            species_id = int(fields[0])
            level = int(fields[1])
        except ValueError as error:
            raise DataError(f"gym {order}: non-numeric team member") from error
        if not 1 <= species_id <= SPECIES_COUNT or not 1 <= level <= 100:
            raise DataError(f"gym {order}: team member out of range")
        members.append(TeamMember(species_id, level))
    if not 1 <= len(members) <= MAX_TEAM_SIZE:
        raise DataError(f"gym {order}: team must have 1-{MAX_TEAM_SIZE} members")
    return tuple(members)


def load_gyms(path: Path) -> list[Gym]:
    with path.open("r", encoding="utf-8", newline="") as source:
        provenance = source.readline().rstrip("\r\n")
        if provenance != PROVENANCE:
            raise DataError("gyms CSV provenance does not match the pinned header")
        reader = csv.DictReader(source)
        if tuple(reader.fieldnames or ()) != HEADERS:
            raise DataError("gyms CSV headers do not match the schema")
        output: list[Gym] = []
        for row in reader:
            try:
                order = int(row["order"])
            except (TypeError, ValueError) as error:
                raise DataError("gyms CSV contains a non-numeric order") from error
            if order != len(output) + 1:
                raise DataError("gym order must be continuous from 1")
            if not row["leader"] or row["type"] not in TYPES:
                raise DataError(f"gym {order}: invalid leader name or type")
            badge = row["badge"]
            if badge == "None":
                badge = ""
            output.append(Gym(order, row["leader"], badge, row["type"], parse_team(row["team"], order)))
    if len(output) != GYM_COUNT:
        raise DataError(f"expected {GYM_COUNT} gym/Elite Four entries, found {len(output)}")
    return output


def generate(gyms: list[Gym]) -> str:
    lines = [
        "// Generated by scripts/generate_pokemon_gyms.py. Do not edit.",
        "#pragma once",
        "",
        "namespace pokemon::generated {",
        "",
    ]
    for gym in gyms:
        lines.append(f"static const char GYM_LEADER_{gym.order:02d}[] = {json.dumps(gym.leader, ensure_ascii=False)};")
        lines.append(f"static const char GYM_BADGE_{gym.order:02d}[] = {json.dumps(gym.badge, ensure_ascii=False)};")
    lines.extend(("", "static const GymTeamMember GYM_TEAM_MEMBERS[] = {"))
    for gym in gyms:
        for member in gym.team:
            lines.append(f"    GymTeamMember{{{member.species_id}, {member.level}}},")
    lines.extend(("};", "", "static const GymData GYMS[] = {"))
    offset = 0
    for gym in gyms:
        lines.append(
            "    GymData{"
            f"GYM_LEADER_{gym.order:02d}, GYM_BADGE_{gym.order:02d}, PokemonType::{gym.type_}, "
            f"{offset}, {len(gym.team)}"
            "},"
        )
        offset += len(gym.team)
    lines.extend(
        (
            "};",
            "",
            "static_assert(sizeof(GYMS) / sizeof(GYMS[0]) == GYM_COUNT);",
            "",
            "}  // namespace pokemon::generated",
            "",
        )
    )
    return "\n".join(lines)


def main() -> int:
    root = Path(__file__).resolve().parents[1]
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", type=Path, default=root / "scripts/data/pokemon-gyms.csv")
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    rendered = generate(load_gyms(args.input))
    if args.check:
        if not args.output.exists() or args.output.read_text(encoding="utf-8") != rendered:
            raise DataError(f"generated gym table is stale: {args.output}")
        return 0
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(rendered, encoding="utf-8", newline="\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
