#!/usr/bin/env python3
"""Generate the Generation I base-stats table from the PokeAPI-sourced CSV."""

from __future__ import annotations

import argparse
import csv
from dataclasses import dataclass
from pathlib import Path

PROVENANCE = "# PokeAPI https://pokeapi.co/api/v2 - generation-i / red-blue"
HEADERS = ("id", "name", "hp", "attack", "defense", "special", "speed")
SPECIES_COUNT = 151


class DataError(RuntimeError):
    pass


@dataclass(frozen=True)
class Stats:
    species_id: int
    hp: int
    attack: int
    defense: int
    special: int
    speed: int


def load_stats(path: Path) -> list[Stats]:
    with path.open("r", encoding="utf-8", newline="") as source:
        provenance = source.readline().rstrip("\r\n")
        if provenance != PROVENANCE:
            raise DataError("stats CSV provenance does not match the pinned PokeAPI source")
        reader = csv.DictReader(source)
        if tuple(reader.fieldnames or ()) != HEADERS:
            raise DataError("stats CSV headers do not match the schema")
        output: list[Stats] = []
        for row in reader:
            try:
                species_id = int(row["id"])
                hp = int(row["hp"])
                attack = int(row["attack"])
                defense = int(row["defense"])
                special = int(row["special"])
                speed = int(row["speed"])
            except (TypeError, ValueError) as error:
                raise DataError("stats CSV contains a non-numeric field") from error
            if species_id != len(output) + 1:
                raise DataError("species IDs must be continuous from 1 through 151")
            for label, value in (("hp", hp), ("attack", attack), ("defense", defense), ("special", special), ("speed", speed)):
                if not 1 <= value <= 255:
                    raise DataError(f"species {species_id}: {label} out of range")
            output.append(Stats(species_id, hp, attack, defense, special, speed))
    if len(output) != SPECIES_COUNT:
        raise DataError(f"expected {SPECIES_COUNT} species, found {len(output)}")
    return output


def generate(stats: list[Stats]) -> str:
    lines = [
        "// Generated by scripts/generate_pokemon_stats.py. Do not edit.",
        "#pragma once",
        "",
        "namespace pokemon::generated {",
        "",
        "static const BaseStats KANTO_BASE_STATS[] = {",
    ]
    for row in stats:
        lines.append(f"    BaseStats{{{row.hp}, {row.attack}, {row.defense}, {row.special}, {row.speed}}},")
    lines.extend(
        (
            "};",
            "",
            "static_assert(sizeof(KANTO_BASE_STATS) / sizeof(KANTO_BASE_STATS[0]) == KANTO_SPECIES_COUNT);",
            "",
            "}  // namespace pokemon::generated",
            "",
        )
    )
    return "\n".join(lines)


def main() -> int:
    root = Path(__file__).resolve().parents[1]
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", type=Path, default=root / "scripts/data/pokemon-stats.csv")
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    rendered = generate(load_stats(args.input))
    if args.check:
        if not args.output.exists() or args.output.read_text(encoding="utf-8") != rendered:
            raise DataError(f"generated stats table is stale: {args.output}")
        return 0
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(rendered, encoding="utf-8", newline="\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
