#!/usr/bin/env python3
"""Generate level-up learnsets and TM/HM compatibility from the PokeAPI-sourced CSVs."""

from __future__ import annotations

import argparse
import csv
from dataclasses import dataclass
from pathlib import Path

PROVENANCE = "# PokeAPI https://pokeapi.co/api/v2 - generation-i / red-blue"
LEARNSET_HEADERS = ("species_id", "level", "move_id")
TMHM_HEADERS = ("species_id", "move_id")
SPECIES_COUNT = 151
MOVE_COUNT = 165


class DataError(RuntimeError):
    pass


@dataclass(frozen=True)
class LearnRow:
    species_id: int
    level: int
    move_id: int


@dataclass(frozen=True)
class TmhmRow:
    species_id: int
    move_id: int


def _read_rows(path: Path, headers: tuple[str, ...]) -> list[dict[str, str]]:
    with path.open("r", encoding="utf-8", newline="") as source:
        provenance = source.readline().rstrip("\r\n")
        if provenance != PROVENANCE:
            raise DataError(f"{path.name}: provenance does not match the pinned PokeAPI source")
        reader = csv.DictReader(source)
        if tuple(reader.fieldnames or ()) != headers:
            raise DataError(f"{path.name}: headers do not match the schema")
        return list(reader)


def load_learnsets(path: Path) -> list[LearnRow]:
    output: list[LearnRow] = []
    previous: tuple[int, int] | None = None
    for row in _read_rows(path, LEARNSET_HEADERS):
        try:
            species_id = int(row["species_id"])
            level = int(row["level"])
            move_id = int(row["move_id"])
        except (TypeError, ValueError) as error:
            raise DataError("learnsets CSV contains a non-numeric field") from error
        if not 1 <= species_id <= SPECIES_COUNT:
            raise DataError(f"learnsets: species {species_id} out of range")
        if not 1 <= move_id <= MOVE_COUNT:
            raise DataError(f"learnsets: species {species_id} references unknown move {move_id}")
        if not 1 <= level <= 100:
            raise DataError(f"learnsets: species {species_id} move {move_id} has invalid level {level}")
        key = (species_id, level)
        if previous is not None and key < previous:
            raise DataError("learnsets CSV must be sorted by species_id then level")
        previous = key
        output.append(LearnRow(species_id, level, move_id))
    return output


def load_tmhm(path: Path) -> list[TmhmRow]:
    output: list[TmhmRow] = []
    previous: tuple[int, int] | None = None
    for row in _read_rows(path, TMHM_HEADERS):
        try:
            species_id = int(row["species_id"])
            move_id = int(row["move_id"])
        except (TypeError, ValueError) as error:
            raise DataError("tmhm CSV contains a non-numeric field") from error
        if not 1 <= species_id <= SPECIES_COUNT:
            raise DataError(f"tmhm: species {species_id} out of range")
        if not 1 <= move_id <= MOVE_COUNT:
            raise DataError(f"tmhm: species {species_id} references unknown move {move_id}")
        key = (species_id, move_id)
        if previous is not None and key < previous:
            raise DataError("tmhm CSV must be sorted by species_id then move_id")
        previous = key
        output.append(TmhmRow(species_id, move_id))
    return output


def generate(learnsets: list[LearnRow], tmhm: list[TmhmRow]) -> str:
    lines = [
        "// Generated by scripts/generate_pokemon_learnsets.py. Do not edit.",
        "#pragma once",
        "",
        "namespace pokemon::generated {",
        "",
        "static const LearnsetEntry LEARN_ENTRIES[] = {",
    ]
    for row in learnsets:
        lines.append(f"    LearnsetEntry{{{row.level}, {row.move_id}}},")
    lines.extend(("};", "", "static const MoveListRef SPECIES_LEARNSET[] = {"))
    offset = 0
    for species_id in range(1, SPECIES_COUNT + 1):
        count = sum(1 for row in learnsets if row.species_id == species_id)
        lines.append(f"    MoveListRef{{{offset}, {count}}},")
        offset += count
    lines.extend(("};", "", "static const uint8_t TMHM_MOVE_IDS[] = {"))
    for row in tmhm:
        lines.append(f"    {row.move_id},")
    lines.extend(("};", "", "static const MoveListRef SPECIES_TMHM[] = {"))
    offset = 0
    for species_id in range(1, SPECIES_COUNT + 1):
        count = sum(1 for row in tmhm if row.species_id == species_id)
        lines.append(f"    MoveListRef{{{offset}, {count}}},")
        offset += count
    lines.extend(
        (
            "};",
            "",
            "static_assert(sizeof(SPECIES_LEARNSET) / sizeof(SPECIES_LEARNSET[0]) == KANTO_SPECIES_COUNT);",
            "static_assert(sizeof(SPECIES_TMHM) / sizeof(SPECIES_TMHM[0]) == KANTO_SPECIES_COUNT);",
            "",
            "}  // namespace pokemon::generated",
            "",
        )
    )
    return "\n".join(lines)


def main() -> int:
    root = Path(__file__).resolve().parents[1]
    parser = argparse.ArgumentParser()
    parser.add_argument("--learnsets-input", type=Path, default=root / "scripts/data/pokemon-learnsets.csv")
    parser.add_argument("--tmhm-input", type=Path, default=root / "scripts/data/pokemon-tmhm.csv")
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    rendered = generate(load_learnsets(args.learnsets_input), load_tmhm(args.tmhm_input))
    if args.check:
        if not args.output.exists() or args.output.read_text(encoding="utf-8") != rendered:
            raise DataError(f"generated learnset table is stale: {args.output}")
        return 0
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(rendered, encoding="utf-8", newline="\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
