#!/usr/bin/env python3
"""Generate the Generation I item table from the hand-authored CSV."""

from __future__ import annotations

import argparse
import csv
import json
from dataclasses import dataclass
from pathlib import Path

PROVENANCE = "# Hand-authored: Generation I (Red/Blue) items, ids 1-6 pinned to EvolutionItem"
HEADERS = ("id", "name", "category", "effect_value", "cures_ailment", "teaches_move_id", "drop_weight")
ITEM_COUNT = 83
MOVE_COUNT = 165
CATEGORIES = {"Stone", "Ball", "Medicine", "StatusCure", "Candy", "PPRestore", "Machine"}
AILMENTS = {"None", "Paralysis", "Sleep", "Freeze", "Burn", "Poison", "Confusion", "All"}
# ids 1-6 must stay in this exact order: they are read back through the
# existing EvolutionItem enum (PokemonTypes.h) so pre-existing pending
# evolution-item events keep decoding correctly after this feature ships.
PINNED_STONE_NAMES = ("Moon Stone", "Fire Stone", "Thunder Stone", "Water Stone", "Leaf Stone", "Link Cable")


class DataError(RuntimeError):
    pass


@dataclass(frozen=True)
class Item:
    item_id: int
    name: str
    category: str
    effect_value: int
    cures_ailment: str
    teaches_move_id: int
    drop_weight: int


def load_items(path: Path) -> list[Item]:
    with path.open("r", encoding="utf-8", newline="") as source:
        provenance = source.readline().rstrip("\r\n")
        if provenance != PROVENANCE:
            raise DataError("items CSV provenance does not match the pinned header")
        reader = csv.DictReader(source)
        if tuple(reader.fieldnames or ()) != HEADERS:
            raise DataError("items CSV headers do not match the schema")
        output: list[Item] = []
        for row in reader:
            try:
                item_id = int(row["id"])
                effect_value = int(row["effect_value"])
                teaches_move_id = int(row["teaches_move_id"])
                drop_weight = int(row["drop_weight"])
            except (TypeError, ValueError) as error:
                raise DataError("items CSV contains a non-numeric field") from error
            if item_id != len(output) + 1:
                raise DataError("item IDs must be continuous from 1")
            if not row["name"] or row["category"] not in CATEGORIES:
                raise DataError(f"item {item_id}: invalid name or category")
            if not 0 <= effect_value <= 255:
                raise DataError(f"item {item_id}: effect_value out of range")
            if row["cures_ailment"] not in AILMENTS:
                raise DataError(f"item {item_id}: invalid cures_ailment")
            if row["category"] == "Machine":
                if not 1 <= teaches_move_id <= MOVE_COUNT:
                    raise DataError(f"item {item_id}: Machine item must reference a valid move")
            elif teaches_move_id != 0:
                raise DataError(f"item {item_id}: only Machine items may set teaches_move_id")
            if not 1 <= drop_weight <= 255:
                raise DataError(f"item {item_id}: drop_weight out of range")
            output.append(
                Item(item_id, row["name"], row["category"], effect_value, row["cures_ailment"], teaches_move_id, drop_weight)
            )
    if len(output) != ITEM_COUNT:
        raise DataError(f"expected {ITEM_COUNT} items, found {len(output)}")
    for index, expected_name in enumerate(PINNED_STONE_NAMES, start=1):
        if output[index - 1].name != expected_name or output[index - 1].category != "Stone":
            raise DataError(f"item {index} must stay {expected_name!r} to match EvolutionItem")
    return output


def generate(items: list[Item]) -> str:
    lines = [
        "// Generated by scripts/generate_pokemon_items.py. Do not edit.",
        "#pragma once",
        "",
        "namespace pokemon::generated {",
        "",
    ]
    for item in items:
        lines.append(f"static const char ITEM_NAME_{item.item_id:03d}[] = {json.dumps(item.name, ensure_ascii=False)};")
    lines.extend(("", "static const ItemData ITEMS[] = {"))
    for item in items:
        lines.append(
            "    ItemData{"
            f"{item.item_id}, ITEM_NAME_{item.item_id:03d}, ItemCategory::{item.category}, "
            f"{item.effect_value}, Ailment::{item.cures_ailment}, {item.teaches_move_id}, {item.drop_weight}"
            "},"
        )
    lines.extend(
        (
            "};",
            "",
            "static_assert(sizeof(ITEMS) / sizeof(ITEMS[0]) == ITEM_COUNT);",
            "",
            "}  // namespace pokemon::generated",
            "",
        )
    )
    return "\n".join(lines)


def main() -> int:
    root = Path(__file__).resolve().parents[1]
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", type=Path, default=root / "scripts/data/pokemon-items.csv")
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    rendered = generate(load_items(args.input))
    if args.check:
        if not args.output.exists() or args.output.read_text(encoding="utf-8") != rendered:
            raise DataError(f"generated item table is stale: {args.output}")
        return 0
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(rendered, encoding="utf-8", newline="\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
