// The contents of this file are generated by ./lib/EpdFont/scripts/build-font-ids.sh
#pragma once

#define LEXENDDECA_10_FONT_ID (1194773887)
#define LEXENDDECA_12_FONT_ID (-1834705648)
#define LEXENDDECA_14_FONT_ID (-1806001351)
#define LEXENDDECA_16_FONT_ID (-2000304501)
#define UI_10_FONT_ID (-1313900173)
#define UI_12_FONT_ID (1544960787)
#define SMALL_FONT_ID (1406075677)

// Font ID 0 is reserved as the "not found" sentinel.
// Guard against any hash accidentally producing 0.
static_assert(LEXENDDECA_10_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(LEXENDDECA_12_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(LEXENDDECA_14_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(LEXENDDECA_16_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(UI_10_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(UI_12_FONT_ID != 0, "Font ID collision with sentinel");
static_assert(SMALL_FONT_ID != 0, "Font ID collision with sentinel");
